name: CI Pipeline

on:
  pull_request:
    branches: [main]

jobs:
 execute:
   runs-on: ubuntu-latest

   steps: 
     - name: Checkout
       uses: actions/checkout@v4.2.0

     - name: Setup Python
       uses: actions/setup-python@v5.2.0

     - name: Run python app
       run: python app1.py
