name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
    - uses: CodeThreat/codethreat-github-action@v1.026
      with:
       distribution: 'zulu' # See 'Supported distributions' for available options
       java-version: '21'
    - run: java shubham1.java
